"""Add client progress photos table

Revision ID: add_client_progress_photos
Revises: 8000b4485d27
Create Date: 2026-04-29 23:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_client_progress_photos'
down_revision = '8000b4485d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_progress_photos',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('before_photo_url', sa.String(length=500), nullable=True),
    sa.Column('after_photo_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_progress_photos')
    # ### end Alembic commands ###
